Update readme.md
osu-translate-zh/awesome-osu pull request #4
Opened 2020-02-25 07:02 UTC by poly000

2020-02-26 05:51 UTC, kj415j45 requested changes

2020-02-26 05:51 UTC, kj415j45 commented on readme.md
> +- `Sayobot` - QQ 机器人，查询玩家信息。目前已挂
小夜称Sayobot仍处于运行状态

2020-02-27 21:01 UTC, poly000 commented on readme.md
> +- `Sayobot` - QQ 机器人，查询玩家信息。目前已挂
> 
> 
> 小夜称Sayobot仍处于运行状态

emmm 只是这个网址失效了的样子

2020-02-27 21:04 UTC, poly000 commented on readme.md
> +- `Sayobot` - QQ 机器人，查询玩家信息。目前已挂
已修改，顺便将镜像的Sayobot链接修改。

2020-02-27 21:05 UTC, poly000 commented on readme.md
> +- `Sayobot` - QQ 机器人，查询玩家信息。目前已挂
但是我没有找到关于机器人的页面……

2020-02-27 21:20 UTC, poly000 commented
顺便
http://osu.yas-online.net 是可以访问的
现在是不进行更新吗？或者被gfw？

2020-03-02 00:24 UTC, merged